props:
  jwt:
    secret: library
    expirationMs: 7200000

server:
  port: 8081

spring:
  output:
    ansi:
      enabled: always
  datasource:
    url: jdbc:h2:mem:library
    username: sa
    password: password
    driver-class-name: org.h2.Driver
  h2:
    console.enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    show-sql: false
#    properties:
 #     hibernate:
  #      format_sql: true
  sql:
    init:
      mode: never
logging:
  file:
    path: src/main/resources
      